version: '3.4'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/app:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: always
    volumes:
      - ./:/app:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: imaga
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
